#CI配置说明 https://q.qq.com/wiki/tools/ci/

name: CI

#写法一：在push事件时触发构建
on: [push] 

#写法二：在master分支的push操作时触发构建
#on:
#  push:
#    branches:
#    - master

jobs:
  build-qq-ci: #job名称

    runs-on: ubuntu-latest #运行环境

    steps:
    
    - name: Checkout 
      uses: actions/checkout@master
      
    - name: Build 
      uses: docker://qqminiapp/build:latest 
      env: 
        #PLUGIN_VERSION: 1.0.0
        #PLUGIN_DESC: CI自动构建上传
        PLUGIN_APPTOKEN: ${{ secrets.APPTOKEN }}
        PLUGIN_BUILDUSER: ${{ github.actor }} 
        PLUGIN_EXPERIENCE: true 
        PLUGIN_USEPACKAGEJSON: true 
        #PLUGIN_FIRSTPAGE: pages/index/index
        #PLUGIN_USEPACKAGEJSON: true
        #PLUGIN_NPMBUILD: true
        #PLUGIN_SOURCECODEPATH: ./test

